//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nohros.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nohros.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array is not long enough to copy all the items in the collection. Check array index and length..
        /// </summary>
        internal static string Arg_ArrayPlusOffTooSmall {
            get {
                return ResourceManager.GetString("Arg_ArrayPlusOffTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index is outside the range of valid indexes for array..
        /// </summary>
        internal static string Arg_IndexOutOfRange {
            get {
                return ResourceManager.GetString("Arg_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid value..
        /// </summary>
        internal static string Arg_OutOfRange {
            get {
                return ResourceManager.GetString("Arg_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range of valid values are {0} to {1}..
        /// </summary>
        internal static string Arg_RangeNotBetween {
            get {
                return ResourceManager.GetString("Arg_RangeNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry with the same key already exists..
        /// </summary>
        internal static string Argument_AddingDuplicate {
            get {
                return ResourceManager.GetString("Argument_AddingDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the specified arguments is a null reference..
        /// </summary>
        internal static string Argument_any_null {
            get {
                return ResourceManager.GetString("Argument_any_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to specify count and offset past end of array..
        /// </summary>
        internal static string Argument_ArrayPlusOffTooSmall {
            get {
                return ResourceManager.GetString("Argument_ArrayPlusOffTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty..
        /// </summary>
        internal static string Argument_Empty {
            get {
                return ResourceManager.GetString("Argument_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string Argument_InvalidOfLen {
            get {
                return ResourceManager.GetString("Argument_InvalidOfLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection.
        ///.
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid control flag..
        /// </summary>
        internal static string Auth_Config_InvalidControlFlag {
            get {
                return ResourceManager.GetString("Auth_Config_InvalidControlFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; is not valid or it was not correctly specified..
        /// </summary>
        internal static string Auth_Config_InvalidModuleType {
            get {
                return ResourceManager.GetString("Auth_Config_InvalidModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control flag was not defined.
        /// </summary>
        internal static string Auth_Config_Missing_ControlFlag {
            get {
                return ResourceManager.GetString("Auth_Config_Missing_ControlFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type was not defined.
        /// </summary>
        internal static string Auth_Config_Missing_LoginModuleType {
            get {
                return ResourceManager.GetString("Auth_Config_Missing_LoginModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A instance of the login module type {0} could not be created..
        /// </summary>
        internal static string Auth_LoginMudule_Type {
            get {
                return ResourceManager.GetString("Auth_LoginMudule_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absoluteExpiration must be DateTime.MaxValue or slidingExpiration must be timeSpan.Zero..
        /// </summary>
        internal static string Caching_Invalid_expiration_combination {
            get {
                return ResourceManager.GetString("Caching_Invalid_expiration_combination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element {0} is already in collection..
        /// </summary>
        internal static string Collection_elm_AddingDuplicate {
            get {
                return ResourceManager.GetString("Collection_elm_AddingDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified collection is a null reference..
        /// </summary>
        internal static string Collection_null {
            get {
                return ResourceManager.GetString("Collection_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for {1}..
        /// </summary>
        internal static string Config_ArgOutOfRange {
            get {
                return ResourceManager.GetString("Config_ArgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error at &quot;{0}&quot;..
        /// </summary>
        internal static string Config_ErrorAt {
            get {
                return ResourceManager.GetString("Config_ErrorAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file is invalid..
        /// </summary>
        internal static string Config_FileInvalid {
            get {
                return ResourceManager.GetString("Config_FileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the specified configuration file..
        /// </summary>
        internal static string Config_FileNotFound {
            get {
                return ResourceManager.GetString("Config_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the file &quot;{0}&quot;..
        /// </summary>
        internal static string Config_FileNotFound_Path {
            get {
                return ResourceManager.GetString("Config_FileNotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified configuration object is not valid..
        /// </summary>
        internal static string Config_InvalidObject {
            get {
                return ResourceManager.GetString("Config_InvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration key &quot;{0}&quot; was not found..
        /// </summary>
        internal static string Config_KeyNotFound {
            get {
                return ResourceManager.GetString("Config_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration information for {0} at {1}..
        /// </summary>
        internal static string Config_MissingAt {
            get {
                return ResourceManager.GetString("Config_MissingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path {0} is not rooted..
        /// </summary>
        internal static string Config_path_is_not_rooted {
            get {
                return ResourceManager.GetString("Config_path_is_not_rooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; path must be relative to the application base directory..
        /// </summary>
        internal static string Config_PathIsRooted {
            get {
                return ResourceManager.GetString("Config_PathIsRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of specified fields is less than the number of columns..
        /// </summary>
        internal static string DataHelper_OrdArrInvalidOfLen {
            get {
                return ResourceManager.GetString("DataHelper_OrdArrInvalidOfLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IDbConnection instance could not be created. Verify if your connection string is valid and if your data source type was correctly specified..
        /// </summary>
        internal static string DataProvider_Connection {
            get {
                return ResourceManager.GetString("DataProvider_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid connection string argument has been supplied, or a required connection string argument has not been supplied..
        /// </summary>
        internal static string DataProvider_ConnectionString {
            get {
                return ResourceManager.GetString("DataProvider_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Provider is invalid..
        /// </summary>
        internal static string DataProvider_InvalidProvider {
            get {
                return ResourceManager.GetString("DataProvider_InvalidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        internal static string Generic_SyntaxError {
            get {
                return ResourceManager.GetString("Generic_SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue empty.
        /// </summary>
        internal static string InvalidOperation_EmptyQueue {
            get {
                return ResourceManager.GetString("InvalidOperation_EmptyQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue full.
        /// </summary>
        internal static string InvalidOperation_FullQueue {
            get {
                return ResourceManager.GetString("InvalidOperation_FullQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root value must be an array or object..
        /// </summary>
        internal static string JSON_BadRootElementType {
            get {
                return ResourceManager.GetString("JSON_BadRootElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence at &quot;{0}&quot;..
        /// </summary>
        internal static string JSON_InvalidEscape {
            get {
                return ResourceManager.GetString("JSON_InvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much nesting..
        /// </summary>
        internal static string JSON_TooMuchNesting {
            get {
                return ResourceManager.GetString("JSON_TooMuchNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing comma not allowed at &quot;{0}&quot;..
        /// </summary>
        internal static string JSON_TrailingComma {
            get {
                return ResourceManager.GetString("JSON_TrailingComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected data after root element..
        /// </summary>
        internal static string JSON_UnexpectedDataAfterRoot {
            get {
                return ResourceManager.GetString("JSON_UnexpectedDataAfterRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary keys must be quoted at &quot;{0}&quot;..
        /// </summary>
        internal static string JSON_UnquotedDictionaryKey {
            get {
                return ResourceManager.GetString("JSON_UnquotedDictionaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid collection of attributes has been supplied, or a required attribute has not been supplied..
        /// </summary>
        internal static string Provider_Attributes {
            get {
                return ResourceManager.GetString("Provider_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly could not be loaded. {0}..
        /// </summary>
        internal static string Provider_LoadAssembly {
            get {
                return ResourceManager.GetString("Provider_LoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required option &quot;{0}&quot; for provider..
        /// </summary>
        internal static string Provider_Option_MissingAt {
            get {
                return ResourceManager.GetString("Provider_Option_MissingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of the requested type could not be created. Check the constructor implied by the {0}..
        /// </summary>
        internal static string Type_CreateInstanceOf {
            get {
                return ResourceManager.GetString("Type_CreateInstanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; could not be loaded..
        /// </summary>
        internal static string Type_Load {
            get {
                return ResourceManager.GetString("Type_Load", resourceCulture);
            }
        }
    }
}
