//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nohros.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nohros.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the array &quot;{0}&quot; should be equals to the length of &quot;{1}&quot;..
        /// </summary>
        internal static string Arg_ArrayLengthDifferFrom {
            get {
                return ResourceManager.GetString("Arg_ArrayLengthDifferFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array lengths must be the same..
        /// </summary>
        internal static string Arg_ArrayLengthsDiffer {
            get {
                return ResourceManager.GetString("Arg_ArrayLengthsDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array is not long enough to copy all the items in the collection. Check array index and length..
        /// </summary>
        internal static string Arg_ArrayPlusOffTooSmall {
            get {
                return ResourceManager.GetString("Arg_ArrayPlusOffTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index is outside the range of valid indexes for array..
        /// </summary>
        internal static string Arg_IndexOutOfRange {
            get {
                return ResourceManager.GetString("Arg_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key {0} was not found..
        /// </summary>
        internal static string Arg_KeyNotFound {
            get {
                return ResourceManager.GetString("Arg_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid value..
        /// </summary>
        internal static string Arg_OutOfRange {
            get {
                return ResourceManager.GetString("Arg_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path {0} is not rooted..
        /// </summary>
        internal static string Arg_PathNotRooted {
            get {
                return ResourceManager.GetString("Arg_PathNotRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; path must be relative to the application base directory..
        /// </summary>
        internal static string Arg_PathRooted {
            get {
                return ResourceManager.GetString("Arg_PathRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range of valid values are {0} to {1}..
        /// </summary>
        internal static string Arg_RangeNotBetween {
            get {
                return ResourceManager.GetString("Arg_RangeNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection that is associated with the specified command should be the same as the specified in the context constructor..
        /// </summary>
        internal static string Arg_TransactionContext_Command_Connection {
            get {
                return ResourceManager.GetString("Arg_TransactionContext_Command_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should be an interface..
        /// </summary>
        internal static string Arg_Type_ShouldBeInterface {
            get {
                return ResourceManager.GetString("Arg_Type_ShouldBeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be of type {1}..
        /// </summary>
        internal static string Arg_WrongType {
            get {
                return ResourceManager.GetString("Arg_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry with the same key already exists..
        /// </summary>
        internal static string Argument_AddingDuplicate {
            get {
                return ResourceManager.GetString("Argument_AddingDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry with the same key already exists. Key:{0}..
        /// </summary>
        internal static string Argument_AddingDuplicateKey {
            get {
                return ResourceManager.GetString("Argument_AddingDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements of the array {0} is less than the number of elements of the array {1}..
        /// </summary>
        internal static string Argument_ArrayLengthMismatch {
            get {
                return ResourceManager.GetString("Argument_ArrayLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to specify count and offset past end of array..
        /// </summary>
        internal static string Argument_ArrayPlusOffTooSmall {
            get {
                return ResourceManager.GetString("Argument_ArrayPlusOffTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot contain null elements..
        /// </summary>
        internal static string Argument_CollectionNoNulls {
            get {
                return ResourceManager.GetString("Argument_CollectionNoNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty..
        /// </summary>
        internal static string Argument_Empty {
            get {
                return ResourceManager.GetString("Argument_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} arugment could not be an empty string..
        /// </summary>
        internal static string Argument_EmptyString {
            get {
                return ResourceManager.GetString("Argument_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} arugment could not be an empty string or a sequence of spaces..
        /// </summary>
        internal static string Argument_EmptyStringOrSpaceSequence {
            get {
                return ResourceManager.GetString("Argument_EmptyStringOrSpaceSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string Argument_InvalidOfLen {
            get {
                return ResourceManager.GetString("Argument_InvalidOfLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the specified arguments is a null reference..
        /// </summary>
        internal static string ArgumentNull_Any {
            get {
                return ResourceManager.GetString("ArgumentNull_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should be a multiple of &quot;{1}&quot;..
        /// </summary>
        internal static string ArgumentOutOfRange_arg_NonMultipleOf {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_arg_NonMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should be a non-negative number..
        /// </summary>
        internal static string ArgumentOutOfRange_arg_NonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_arg_NonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection.
        ///.
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-negative number required..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; is not valid or it was not correctly specified..
        /// </summary>
        internal static string Auth_Config_InvalidModuleType {
            get {
                return ResourceManager.GetString("Auth_Config_InvalidModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control flag was not defined.
        /// </summary>
        internal static string Auth_Config_Missing_ControlFlag {
            get {
                return ResourceManager.GetString("Auth_Config_Missing_ControlFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type was not defined.
        /// </summary>
        internal static string Auth_Config_Missing_LoginModuleType {
            get {
                return ResourceManager.GetString("Auth_Config_Missing_LoginModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A instance of the login module type {0} could not be created..
        /// </summary>
        internal static string Auth_LoginMudule_Type {
            get {
                return ResourceManager.GetString("Auth_LoginMudule_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absoluteExpiration must be DateTime.MaxValue or slidingExpiration must be timeSpan.Zero..
        /// </summary>
        internal static string Caching_Invalid_expiration_combination {
            get {
                return ResourceManager.GetString("Caching_Invalid_expiration_combination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element {0} is already in collection..
        /// </summary>
        internal static string Collection_AddingDuplicate {
            get {
                return ResourceManager.GetString("Collection_AddingDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified collection is a null reference..
        /// </summary>
        internal static string Collection_null {
            get {
                return ResourceManager.GetString("Collection_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration key &quot;{0}&quot; was not found..
        /// </summary>
        internal static string Config_KeyNotFound {
            get {
                return ResourceManager.GetString("Config_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for {1}..
        /// </summary>
        internal static string Configuration_ArgOutOfRange {
            get {
                return ResourceManager.GetString("Configuration_ArgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} does not represent a valid configuration file..
        /// </summary>
        internal static string Configuration_InvalidFormat {
            get {
                return ResourceManager.GetString("Configuration_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration information for &quot;{0}&quot; at &quot;{1}&quot;..
        /// </summary>
        internal static string Configuration_Missing {
            get {
                return ResourceManager.GetString("Configuration_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration node {0} is not defined..
        /// </summary>
        internal static string Configuration_MissingNode {
            get {
                return ResourceManager.GetString("Configuration_MissingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A replica could not be created because the group &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string Configuration_providers_inexistent_replicas_group {
            get {
                return ResourceManager.GetString("Configuration_providers_inexistent_replicas_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options for the provider &quot;{0}&quot; contains references that cannot be resolved..
        /// </summary>
        internal static string Configuration_providers_missing_reference {
            get {
                return ResourceManager.GetString("Configuration_providers_missing_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replica nodes could not have a option that references another option.
        ///Remove any option that has the following pattern &lt;option ref=&quot;&quot;/&gt;.
        /// </summary>
        internal static string Configuration_providers_replicas_with_ref_options {
            get {
                return ResourceManager.GetString("Configuration_providers_replicas_with_ref_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options reference &quot;{0}&quot; could not be resolved..
        /// </summary>
        internal static string Configuration_providers_unresolved_reference {
            get {
                return ResourceManager.GetString("Configuration_providers_unresolved_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IDbConnection instance could not be created. Verify if your connection string is valid and if your data source type was correctly specified..
        /// </summary>
        internal static string DataProvider_Connection {
            get {
                return ResourceManager.GetString("DataProvider_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid connection string argument has been supplied, or a required connection string argument has not been supplied..
        /// </summary>
        internal static string DataProvider_ConnectionString {
            get {
                return ResourceManager.GetString("DataProvider_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no transaction in progress..
        /// </summary>
        internal static string DataProvider_InvalidOperation_NoTransaction {
            get {
                return ResourceManager.GetString("DataProvider_InvalidOperation_NoTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not permitted when the transaction is in completed..
        /// </summary>
        internal static string DataProvider_InvalidOperation_TransactionCompleted {
            get {
                return ResourceManager.GetString("DataProvider_InvalidOperation_TransactionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Provider is invalid..
        /// </summary>
        internal static string DataProvider_InvalidProvider {
            get {
                return ResourceManager.GetString("DataProvider_InvalidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} =&gt; The current transaction context is not compatible with this class..
        /// </summary>
        internal static string DataProvider_TransactionContextRace {
            get {
                return ResourceManager.GetString("DataProvider_TransactionContextRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        internal static string Format_SyntaxError {
            get {
                return ResourceManager.GetString("Format_SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cast from {0} to {1}..
        /// </summary>
        internal static string InvalidCast_FromTo {
            get {
                return ResourceManager.GetString("InvalidCast_FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method has already been called once..
        /// </summary>
        internal static string InvalidOperation_CalledMoreThanOnce {
            get {
                return ResourceManager.GetString("InvalidOperation_CalledMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue is empty..
        /// </summary>
        internal static string InvalidOperation_EmptyQueue {
            get {
                return ResourceManager.GetString("InvalidOperation_EmptyQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue is full..
        /// </summary>
        internal static string InvalidOperation_FullQueue {
            get {
                return ResourceManager.GetString("InvalidOperation_FullQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing comma not allowed at &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidOperation_json_TrailingComma {
            get {
                return ResourceManager.GetString("InvalidOperation_json_TrailingComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected data after root element..
        /// </summary>
        internal static string InvalidOperation_json_UnexpectedDataAfterRoot {
            get {
                return ResourceManager.GetString("InvalidOperation_json_UnexpectedDataAfterRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary keys must be quoted at &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidOperation_json_UnquotedDictionaryKey {
            get {
                return ResourceManager.GetString("InvalidOperation_json_UnquotedDictionaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much nesting..
        /// </summary>
        internal static string InvalidOperation_TooMuchNesting {
            get {
                return ResourceManager.GetString("InvalidOperation_TooMuchNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root value must be an array or object..
        /// </summary>
        internal static string JSON_BadRootElementType {
            get {
                return ResourceManager.GetString("JSON_BadRootElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence at &quot;{0}&quot;..
        /// </summary>
        internal static string JSON_InvalidEscape {
            get {
                return ResourceManager.GetString("JSON_InvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} method of {1} throws an exception..
        /// </summary>
        internal static string Log_MethodThrowsException {
            get {
                return ResourceManager.GetString("Log_MethodThrowsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} throws an exception..
        /// </summary>
        internal static string Log_ThrowsException {
            get {
                return ResourceManager.GetString("Log_ThrowsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout has been failedfor module {0}..
        /// </summary>
        internal static string Login_LogoutFails {
            get {
                return ResourceManager.GetString("Login_LogoutFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot map the [{0}] interface directly.
        ///You should define a factory to create an instance of the interface using the SetFactory method..
        /// </summary>
        internal static string Mappers_CannotMapInterfaces {
            get {
                return ResourceManager.GetString("Mappers_CannotMapInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method cannot be used to create types related to {0}..
        /// </summary>
        internal static string NotSupported_CannotCreateType {
            get {
                return ResourceManager.GetString("NotSupported_CannotCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the assembly was not specified..
        /// </summary>
        internal static string Provider_AssemblyNotSpecified {
            get {
                return ResourceManager.GetString("Provider_AssemblyNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid collection of attributes has been supplied, or a required attribute has not been supplied..
        /// </summary>
        internal static string Provider_Attributes {
            get {
                return ResourceManager.GetString("Provider_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly could not be loaded. {0}..
        /// </summary>
        internal static string Provider_LoadAssembly {
            get {
                return ResourceManager.GetString("Provider_LoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required option &quot;{0}&quot; for provider..
        /// </summary>
        internal static string Provider_Option_MissingAt {
            get {
                return ResourceManager.GetString("Provider_Option_MissingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to copy the value elements of a SkipList to an array that is too small..
        /// </summary>
        internal static string SkipList_BadArrayCopyTo {
            get {
                return ResourceManager.GetString("SkipList_BadArrayCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to access a SkipListEnumerator that is positioned before the first element of a SkipList or after the last element..
        /// </summary>
        internal static string SkipList_BadEnumAccess {
            get {
                return ResourceManager.GetString("SkipList_BadEnumAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to pass an out of range index to the CopyTo method of a SkipList..
        /// </summary>
        internal static string SkipList_BadIndexCopyTo {
            get {
                return ResourceManager.GetString("SkipList_BadIndexCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SkipList was set to use the IComparable interface and an attempt was made to add a key that does not support this interface..
        /// </summary>
        internal static string SkipList_ComparableError {
            get {
                return ResourceManager.GetString("SkipList_ComparableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkipListEnumerator is no longer valid. The SkipList has been modified since the creation of this enumerator..
        /// </summary>
        internal static string SkipList_InvalidEnum {
            get {
                return ResourceManager.GetString("SkipList_InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to add an element in which the key of the element already exists in the SkipList..
        /// </summary>
        internal static string SkipList_KeyExistsAdd {
            get {
                return ResourceManager.GetString("SkipList_KeyExistsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to pass a null array to the CopyTo method of a SkipList..
        /// </summary>
        internal static string SkipList_NullArrayCopyTo {
            get {
                return ResourceManager.GetString("SkipList_NullArrayCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to pass a null key to a SkipList..
        /// </summary>
        internal static string SkipList_NullKey {
            get {
                return ResourceManager.GetString("SkipList_NullKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required switch &quot;{0}&quot;..
        /// </summary>
        internal static string Switches_MissingSwitch {
            get {
                return ResourceManager.GetString("Switches_MissingSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast object of type &quot;{0}&quot; to type &quot;{1}&quot;..
        /// </summary>
        internal static string Type_InvalidCastException {
            get {
                return ResourceManager.GetString("Type_InvalidCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an instance of the type &quot;{0}&quot;, because:
        ///.
        /// </summary>
        internal static string TypeLoad_CreateInstance {
            get {
                return ResourceManager.GetString("TypeLoad_CreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default constructor was not found..
        /// </summary>
        internal static string TypeLoad_DefaultConstructorNotFound {
            get {
                return ResourceManager.GetString("TypeLoad_DefaultConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A constructor with the following signature .ctor({0}) was not found..
        /// </summary>
        internal static string TypeLoad_MissingConstructor {
            get {
                return ResourceManager.GetString("TypeLoad_MissingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type was not found..
        /// </summary>
        internal static string TypeLoad_TypeNotFound {
            get {
                return ResourceManager.GetString("TypeLoad_TypeNotFound", resourceCulture);
            }
        }
    }
}
